# This file is for running the app LOCALLY.
# E:/file sharing system/.streamlit/secrets.toml

base_url = "https://file-sharing-ghost-of-uchiha.streamlit.app/"

[email]
sender = "b1071g5@gmail.com"
password = "cruf iyvr xybe oewe"

[cloudinary]
cloud_name = "dtymxkox4"
api_key = "622887981598471"
api_secret = "3MOS_k-5b_xBm5tzECO3nxIiqvc"


# --- Fill this section from your original serviceaccountkey.json file ---
[firebase]
type = "service_account"
project_id = "file-sharing-9746c"
private_key_id = "b42201caff4699204cab113841746a5071ac97f9"
client_email = "firebase-adminsdk-fbsvc@file-sharing-9746c.iam.gserviceaccount.com"
client_id = "117629002569763308183"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40file-sharing-9746c.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

# The private_key from your JSON file goes inside the triple quotes.
private_key = """-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC+KrFOUgbsrieh\nHbPg3tzyrxg8h3ZzRWBF4LBbc+ougGngzdUrpWA1CegNRZeAb9t3T+d/eCfsGhkj\nQWYj2WqILAmweq7ANduW8mt2kpRjo4SizxREvBvQTIYTeFn8Pk7cuVGHM4qpf2Eu\nweYTYYetjrNoH48zX7Qx9uKM6hsiR0h/xLnrP2W4sIu2icGpsfVTojxmovtI6Z6F\nLn3B9tcJyKsDHp21+CSYqun8ZC/BhKbMGgcq1vUiFZk1njzk1Uy3gDynsPs31yBg\nwvwq0XJeOScSoIgzUWgftfRN3yut6iqpMllp2cEMH8E6nFWB/GOF2ueLwbYMPHlG\nZo+Rb7QXAgMBAAECggEABEdMnvD8g+W1MYxMCEKrYPBskKwRj61faaMRBLW6bppo\nB21KHwXFANx8spO+wV6C5w/OqxEGgOrjZuYpSKQzH+Yxv507AksT6jUBEvVgTk+X\nA9y53YQH8itOlvCNwb2bI58txOd1drPNeXJWXVhD57U+txiCrcq48KjX1wjLXH2J\nFsFSw7ZgkrDbobfKQ6W0pOtUEIp6e3zO4OkkN8SvgKMgC7mBYkLr4Gh8d3ggy0fO\nU7KPRtNP6YlDi6hheoQHEtx49Cs7Ihtc0RNNREoNI97ubitlsRd+0APL2bjZL/cj\neu2Mf9MyanQ0P4ZJqLTrMLrrqAR3W4gM4Y/0xLFzrQKBgQD3w1OvVE/b89/R/U7U\ng/th5xbWkFldEeOlv/F9uhbrzNFCFvH4K0nK/1jo4WxC4fRGtnslMquJOQpI33o2\noAzVAzZs2ACKim36CbfHaZNKC4tZx5obude6ZckwyF8IuE7BhCgFsB2xFvEB/eg/\nrq95vjCxF6VvInS4KfokvR1qowKBgQDEfSxI/8bGb8Ehcn6NwUfBwiSeX1oFWZwW\nggto6WvlGwB+N4QLaMXDtY6eaUD5Ct1E/9nq2Ajqw8XD+tSSDJ3ULNuu4teJ4VLE\nK3Htuq1JEEHuyKrzduzkESYq/qbIRreL21WaaPfU/Pl/esQGuLkul/zJsUoiR7lF\nvFqmnWt7/QKBgBXodKblOqaFWv4zetv5y6mtiGxymSRMp6eJYG4wnUQ+eSZx5vV9\nxmmnyJHXFP6ZAkOacSsp3tckbw9gi2r3Hgtb3F0lgG6/rNfWMiT05ew/NxQ6PRtE\nhJnb1D13Ckg4G+aqq+tM1mNJVwhJDldLOAL42U9feuZn0pBSTecfvdEnAoGASjQz\ne0YNHXeq6iTBImux27yj86Ny7b5PsjhecrpkYtt1rjTtCxoARc7VE4IQZXzy31H4\nTDZV98MDduXNTXKyUCS4ui001P9hMHBv0CXFt2gKXlEuLk/lWqQXU/ljpxL90jV8\n+JlXrvnyh3Ang5pTZQNFFi58HsITeACQA4hDxUkCgYEA12E1L3ncgUmg3jfLf6Je\nx7/A/FZQTDm8D4c0R4pIkizfhdniaG8ndLmRVGiSOte8YDQ6txbkxeU4eu6YMtWY\nPBC3Z74Zurd+r44gqDhTyDvWaukjExJV/kLmc2i2fKtbDQigjqRsnUYUzIcUQhBe\n6yIYAJL6GboBqOaXv9SK2Xk=\n-----END PRIVATE KEY-----\n"""